apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-push
spec:
  inputs:
    resources:
      - name: git-source
        type: git
  params:
    - name: pathToDockerFile
      description: The path to the dockerfile to build
      default: /workspace/git-source/registry/example/helloworld/Dockerfile
    - name: pathToContext
      description: >-
        The build context used by Kaniko
        (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
      default: /workspace/git-source/registry/example/helloworld
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: update-image
      image: quay.io/rhdevelopers/tutorial-tools:0.0.3
      command:
        - yq
      args:
        - "w"
        - "-i"
        - "-d*"
        - "./deployment.yaml"
        - "spec.template.spec.containers[0].image"
        - "${outputs.resources.builtImage.url}"
      workingDir: /workspace/git-source/registry/example