apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  resources:
    inputs:
      - name: git-source
        type: git
  steps:
    - name: deploy-app
      image: quay.io/rhdevelopers/tutorial-tools:0.0.3
      command:
        - kubectl
      args:
        - "apply"
        - "--filename=./deployment.yaml"
        - "--filename=./service.yaml"
        # - "--filename=./ingress.yaml"
      workingDir: /workspace/git-source/registry/example
