apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: hello-world
  # generateName: picalc-pr-
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  resources:
    - name: git-source
      resourceRef:
        name: hello-git-source
    - name: builtImage
      resourceRef:
        name: helloworld-image
  serviceAccountName: build-robot
